project_id = "jdouvqndemcidjjkepgm"

[functions.send-invite]
verify_jwt = false

[functions.bulk-create-products]
verify_jwt = false

[functions.get-all-contacts]
verify_jwt = false
[functions.send-order-approval-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-order-approval-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-order-approval-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-order-approval-email/*.html" ]
