// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdouvqndemcidjjkepgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkb3V2cW5kZW1jaWRqamtlcGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDA0ODEsImV4cCI6MjA3MzgxNjQ4MX0.qEI2HGWh5zBQLI9f8tK99svbVRojbR3VMZwguRZnxJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});